version: "3.5"
services:
  verification-oracle-staging:
    image: ghcr.io/near-ndc/verification-oracle:develop
    restart: always
    command:
      - ./verification-oracle
    ports:
      - 8081:8081
    logging:
      options:
        max-size: 250m
        max-file: 3
    extra_hosts: []
    volumes:
      - type: bind
        source: /root/Projects/verification-oracle/config/staging.json
        target: /app/config/default.json
      - type: bind
        source: /root/Projects/verification-oracle/config/staging-secrets.json
        target: /app/config/local.json
    deploy:
      resources:
        limits:
          memory: 1000M
    environment:
      RUST_LOG: debug
    init: false
  verification-oracle-production:
    image: ghcr.io/near-ndc/verification-oracle:main
    restart: always
    command:
      - ./verification-oracle
    ports:
      - 8080:8080
    logging:
      options:
        max-size: 250m
        max-file: 3
    extra_hosts: []
    volumes:
      - type: bind
        source: /root/Projects/verification-oracle/config/production.json
        target: /app/config/default.json
      - type: bind
        source: /root/Projects/verification-oracle/config/production-secrets.json
        target: /app/config/local.json
    deploy:
      resources:
        limits:
          memory: 1000M
    environment:
      RUST_LOG: debug
    init: false
